apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: velero-ui-auth
  namespace: velero-ui
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault
    kind: ClusterSecretStore
  target:
    name: velero-ui-auth
    template:
      data:
        admin-user: "{{ `{{ .username }}` }}"
        admin-password: "{{ `{{ .password }}` }}"
  data:
    - secretKey: username
      remoteRef:
        key: "/velero-ui"
        property: username
    - secretKey: password
      remoteRef:
        key: "/velero-ui"
        property: password
